apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gf5j
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gf5j
    app.kubernetes.io/part-of: integ-app-druw
  name: hacbs-test-project-gf5j
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gf5j
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gf5j
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-mpig-tenant/integ-app-druw/hacbs-test-project-gf5j@sha256:8ca41f2b397b65cb2f5b24021a5ac7548e7a5a8fe65b336777a2288f114b867a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
